### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by RinatValiullov** [nin-jin/meme.hyoo.ru#1]
I removed the default picture and labels in the application.
After refreshing the [page](https://meme.hyoo.ru), they do not appear.
How to return an initial picture and labels?

My environment:

Chrome browser
Version 95.0.4638.69 (Official Build) (64-bit)

**Comment by nin-jin** [comment]
You can upload your custom image instead. May be we will add gallery later.

**Comment by RinatValiullov** [comment]
Ok. Thanks.
Can I close this issue?

**Comment by nin-jin** [comment]
Your issue - your power.
